### ISSUE TITLE
Icon reflections not consistent - size matters :-)

### ISSUE THREAD

**Issue by recuerom** [w0lfschild/cDock-Issue-Tracker#105]
see sample attached, obviously the size of the icon affects the quality of the reflection. For me the first and the last icons have a decent reflection. The other 4 barely noticeable, not sure what you can do about it but it would be nice if all reflections started at the base of the icon regardless of size. If the intensity of the reflection could have a slide to custom to suit it would also enhance the look.
<img width="385" alt="screenshot of banktivity" src="https://user-images.githubusercontent.com/15388514/38891711-7e33d8f8-42c8-11e8-8e11-83bb574218c0.png">

**Comment by minimum91** [comment]
This depends on any individual icon. This can not be fixed in cDock.

**Comment by recuerom** [comment]
Thanks for that, i just started playing with shadows option and I am very happy with the outcome. Icon reflections need to be higher and more intense to be of aesthetic value in a 3D image.

**Comment by w0lfschild** [comment]
Yup apps with more transparent space around the icon will have the reflection appear farther away, not really something that's fixable by cDock.
