### ISSUE TITLE
Doesn't always start - Mojave

### ISSUE THREAD

**Issue by brousseau6933** [w0lfschild/cDock-Issue-Tracker#188]
Hello,

Sometimes it starts, sometimes I have to restart the Dock in the cDock preferences...
cDock helper is in my start items...

Thanks,

Patrice

**Comment by r3volution11** [comment]
I have this same issue. More often than not I have to load up the app and click Apply Changes and Restart to get it into gear.

**Comment by recuerom** [comment]
Same issue/action as R3volution. I have played with the startup order thru Startupizer but more often than not needs to go into Apply Changes to activate.

**Comment by jesusvallez** [comment]
Same here

**Comment by PsyCoGeek** [comment]
Ok, so where's the developer with any news on a fix???

**Comment by gabrielfsousa** [comment]
same here,

**Comment by gabrielfsousa** [comment]
added on login items /Applications/cDock.app/Contents/Resources/cDock Helper.app

osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/cDock.app/Contents/Resources/cDock Helper.app", hidden:false}'

and now on cdock starts on login

**Comment by jesusvallez** [comment]
@gabrielfsousa can you explain it better?

thanks you

**Comment by brousseau6933** [comment]
Yes, I would like to know the procedure for the workaround?

Thanks,

Patrice

Envoyé de mon iPad

**Comment by gabrielfsousa** [comment]
in my case i didnt have cdock in login items

![image](https://user-images.githubusercontent.com/722744/54150142-af7f0680-442f-11e9-91d3-5de77c5ddac7.png)

so i added with this command 
```
osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/cDock.app/Contents/Resources/cDock Helper.app", hidden:false}'
```

**Comment by r3volution11** [comment]
In other words for the less technical users, they should run the `osascript` line in a terminal and that will do the trick.

This will load only the helper that does the work on the Dock and not the main app for changing settings.

**Comment by meat-ball** [comment]
I'm not sure if this is related to the OP post. The problem some of us are running into is not the helper or cdock not starting but the changes arent actually taking place. Or maybe I misunderstood but this is where I'm running into issues. It's launching fine and my settings will stay in place but most of the time if I want to make a change it takes a lot of setting and resetting to get anything to work. Once it does it usually stays in place (for me anyway).

![image](https://user-images.githubusercontent.com/5460919/54159640-afb8db00-440a-11e9-8b03-79b50d05d320.png)

**Comment by r3volution11** [comment]
It looks like there are two possible problems causing the issue we all have experienced.

One is solved after ensuring cDock Helper is properly added as a login item.

The other, which requires multiple "Apply Settings and Restart" of the app to activate, does not yet have a known solution.

**Comment by meat-ball** [comment]
Sounds about right. We may need to fix this ourselves as I'm not sure @w0lfschild is still developing for it.

**Comment by goblintim** [comment]
in /Applications/cDock.app/Contents/Resources/cDock Helper.app, when i get there, there i no cdock helper app?

**Comment by w0lfschild** [comment]
@goblintim 

Maybe try downloading a new copy of cDock?

**Comment by goblintim** [comment]
if you think that will work, i just down loaded it last week, and bought it yesterday

**Comment by w0lfschild** [comment]
I know this issue might not be `Solved` but I'm closing it as there's not really anything I can do to my knowledge.

The code is literally a one liner so I'm not sure what could be going wrong. Maybe folks in this thread are moving the app somewhere odd.

```objectivec
SMLoginItemSetEnabled((CFStringRef)@"com.macenhance.cDockHelper", true);
```

https://developer.apple.com/documentation/servicemanagement/1501557-smloginitemsetenabled?language=objc

Also the path for the helper has changed to `/Applications/cDock.app/Contents/Library/LoginItems/cDock Helper.app` in cDock 4 for anyone who wants to manually add it to login items.
