### ISSUE TITLE
Can't disable cDock.

### ISSUE THREAD

**Issue by anasard** [w0lfschild/cDock-Issue-Tracker#190]
#**Describe the bug**
I've chosen the "default" theme from the list of themes and it's not changing it. And I have also deleted the app and rebooted my computer multiple times to see if that would work, but the dock never returns to its original design. 
I just want to disable cDock, but I don't know how. 

**To Reproduce**
click on "default" theme
click on refresh dock 
*doesnt change
Delete the app
reboot computer
doesnt change

**Expected behavior**
Reset my dock to its factory default design. Like if I had never used cDock
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mojave
 - Version 10.14.1

Thanks in advance for your help. :)

**Comment by jruck** [comment]
I'm having this issue myself. I'd like to disable cDock on one of my machines. But even after uninstalling the app, the customizations still persist. How can I return my dock to its pre-cDock state?

**Comment by w0lfschild** [comment]
Delete the file `/Library/Application Support/MacEnhance/Plugins/cDock.bundle`
