### ISSUE TITLE
Just bought cDock, have one more suggestion

### ISSUE THREAD

**Issue by q64ceo** [w0lfschild/cDock-Issue-Tracker#269]
I would like to have a picture selection to pick the separator

The Mac OS X Leopard dock separator is nice and it would go well with the dock

**Comment by w0lfschild** [comment]
I think this feature will eventually be added in v4. Until then, closing this and linking to the older duplicate issue.

https://github.com/w0lfschild/cDock-Issue-Tracker/issues/72
