### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by avincent98144** [w0lfschild/cDock-Issue-Tracker#271]
been using your great app for a couple weeks now and have noticed:

- despite toggling badges on, they have disappeared globally.

- despite toggling on, labels have disappeared globally.

Let me know what you need [log files, screenshots, etc.] to jumpstart troubleshooting.

Mojave 10.14.6

cheers!

**Comment by w0lfschild** [comment]
- Badges only show once an app has opened. If the Dock restarts they will be hidden until the app launches again.

- Not sure about the second one. Do you have any accessibility settings on?

**Comment by avincent98144** [comment]
badges NEVER show no matter what state.  

and no, nothing in accessibility is ON.

please advise.

**Comment by avincent98144** [comment]
Following up

**Comment by avincent98144** [comment]
Following up

**Comment by w0lfschild** [comment]
I'm honestly not sure.
I've never heard this from anyone else and I don't see how it could be happening in terms of the code.
You could try cDock v4, which has changed the label code but iirc the badge code is the same.

**Comment by w0lfschild** [comment]
I also suppose a video could maybe help that shows your settings and then you triggering a badge to show up on the terminal icon.
