### ISSUE TITLE
user

### ISSUE THREAD

**Issue by goblintim** [w0lfschild/cDock-Issue-Tracker#283]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
everytime i restart my computer, i have to open cdock and restart it, the old one never had that problem?

**Comment by goblintim** [comment]
imac OS catalina 10.15.6

**Comment by w0lfschild** [comment]
What exactly is the issue? You just posted the issue template...

**Comment by goblintim** [comment]
everytime i restart my computer, i have to open cdock and restart it, the old one never had that problem?

**Comment by goblintim** [comment]
i posted it but it showed up in the template lol, i was using the rfree version for 4 days and after i purchased it yesterday, thats when this happened. i have an imac with os catalina, catalina messed a lot up on my mac

**Comment by w0lfschild** [comment]
Check out this issue thread https://github.com/w0lfschild/cDock2/issues/188
