### ISSUE TITLE
Activating CDock

### ISSUE THREAD

**Issue by BeeJaythedj** [w0lfschild/cDock-Issue-Tracker#284]
Activating not accepting. 

CDOCK won't accept my activation key. Order #3246403
purchased on Thursday 22nd March 2018. 

NOW it doesn't work. :(

**Comment by w0lfschild** [comment]
Hello,

cDock 4 is a separate license from cDock 3.

If you want, you’re free to continue using cDock 3 on macOS 10.15 and below. You can download the latest version (3.1.2) here : https://github.com/w0lfschild/app_updates/blob/master/cDock3/cDock.3.1.2.zip
It, and older versions, are also available on my website under the changelog tab. https://www.macenhance.com/cdock
If you’ve lost you license key or used all your available activations you can ask to have your key reset by sending the email you used to purchase the key but this won’t upgrade your license from v3 to v4 

If you’ve updated to macOS 11 or you just want to use the new features of cDock 4 you’ll have to get a new license. Which are currently on sale before and probably shortly after Big Sur goes live.

Thanks for your interest in cDock.

- MacEnhance Support
