### ISSUE TITLE
cDock 3.0.9 show "cDock needs to update some..." after enable SIP

### ISSUE THREAD

**Issue by paohuoche** [w0lfschild/cDock-Issue-Tracker#289]
My system is High sierre, and install cDock 3.0.9.
First I disabled SIP and installed successfully, but when re-enable SIP, the cDock doesn't work, the dock return to default style.
And the app show a message below: 

<img width="858" alt="屏幕快照 2020-09-23 下午2 05 45" src="https://user-images.githubusercontent.com/7116988/93972960-f4665600-fda5-11ea-9154-80b6235cb6d4.png">

**Comment by w0lfschild** [comment]
You need to leave SIP off for cDock to function properly.

**Comment by paohuoche** [comment]
This is a joke

**Comment by paohuoche** [comment]
> You need to leave SIP off for cDock to function properly.

This is a joke

**Comment by w0lfschild** [comment]
@paohuoche how is it a joke?

Code injection is restricted by SIP, **cDock is code injection**.
