### ISSUE TITLE
Dock crashing Big Sur Beta 6+

### ISSUE THREAD

**Issue by joshuadlieberman** [w0lfschild/cDock-Issue-Tracker#291]
Hi, for some reason I can't seem to get the themes to apply with this version of CDock and the latest Big Sur Beta 8 for developers. I click on the theme and nothing happens, then when I click on a setting or the apply and restart the dock button the dock restarts (takes a minute or so) and still nothing happens...

**Comment by NormG1** [comment]
Same problem. I had to roll back to V3, which does work on Catalina. I have decided not to participate in the Big Sur beta at this time, although I did load it on an external drive just to see it in action.

**Comment by joshuadlieberman** [comment]
NormG1, that was probably smart... I was a bit too impatient for the new design elements.

**Comment by w0lfschild** [comment]
A fix will be released soon.

**Comment by w0lfschild** [comment]
You can use this until I publicly release something

https://github.com/w0lfschild/app_updates/raw/master/Beta/cDock_4.3.2.zip
