### ISSUE TITLE
Security Update 2020-005 Mojave

### ISSUE THREAD

**Issue by omnidelic** [w0lfschild/cDock-Issue-Tracker#292]
After installing the update cDock appears to be trying to load but the desktop flashes black every second and the fan runs up making the computer unusable. Only way to stop it is to delete cDock. Worked fine before the update and verified that System Integrity is still turned off after. Tried a clean install but it failed midway through (after the first password request) with a message to contact the maintainer.

**Comment by w0lfschild** [comment]
General response to the issue:

This is going out as a response to many people who have contacted us regarding Security Update 2020-005 Mojave
https://support.apple.com/en-us/HT211849

As you have probably already noticed cDock and MacForge are broken with this update. After some investigation it’s at this point something I’m unlikely going to be able to fix.

This leaves a few options for you:
1. Reinstall Mojave https://support.apple.com/en-us/HT204904 and then do not install Security Update 2020-005 Mojave 
2. Update to Catalina https://apps.apple.com/us/app/macos-catalina/id1466841314
3. Stop using cDock (and/or MacForge) and delete this folder /Library/Application Support/MacEnhance/Plugins  

There is a final option which is semi-complex if you want to keep using cDock and can’t update but also refuse to not install the security patch:
1. Download and install [mySIMBL](https://github.com/w0lfschild/mySIMBL)
2. Copy /Library/Application Support/MacEnhance/Plugins/cDock.bundle to /Library/Application Support/SIMBL/Plugins/cDock.bundle
3. Delete /Library/Application Support/MacEnhance/Plugins/cDock.bundle/Contents (not the main bundle, just the contents)
4. Lock /Library/Application Support/MacEnhance/Plugins/cDock.bundle (to prevent modifications)

For an explanation of what’s happening:
1. cDock and MacForge use [mach_inject](https://github.com/rentzsch/mach_inject) to load code into the Dock process
2. After the security update any process being injected into using [mach_inject](https://github.com/rentzsch/mach_inject) immediately crashes. 
Conclusion:

1. Unfortunately unless a fix is made by someone else or Apple releases another update no fixes will come for cDock.
2. Mainly for the following reasons 
    1. We don’t write or maintain [mach_inject](https://github.com/rentzsch/mach_inject)
    2. The same issue isn’t present in the same security patch for 10.15 or the 11.0 Betas. (which the majority of users are running)
    3. cDock will work on 10.14.16 if you do not install the latest patch
3. It’s possible we will release a patcher that can apply the fix detailed above on 10.14.6 but no ETA

**Comment by omnidelic** [comment]
Having already installed the security patch I went ahead and tried the fix. I may have done it wrong. The mySIMBL link took me to the MacForge download which of course didn't work. I tried manually creating the SIMBL folder since that didn't exist and copying the bundle but that didn't work. Is there a different link to download mySIMBL?

**Comment by w0lfschild** [comment]
@omnidelic 

Honestly you're probably better off just re-installing Mojave.

Apple has officially pulled the Security Update 2020-005 so I would say the fault is with Apple and not cDock. https://www.macrumors.com/2020/10/01/apple-pulls-macos-mojave-security-update/

But either way here's all mySIMBL versions: https://github.com/w0lfschild/app_updates/tree/master/mySIMBL

**Comment by omnidelic** [comment]
Thanks, that worked. Software Update is still showing Security Update 2020-005 this morning, hoping they really do pull it!

**Comment by w0lfschild** [comment]
You can now install the fixed update Apple released and everything should work without any workarounds.

**Comment by omnidelic** [comment]
Confirmed, thanks for letting me know!
