### ISSUE TITLE
Big Sur compatiblity

### ISSUE THREAD

**Issue by theobrinkman** [w0lfschild/cDock-Issue-Tracker#296]
Hi

Can you tell me iff cDock is compatible with OS Big Sur and if not can we expect an updated version of cDock?

Regards

Theo

**Comment by w0lfschild** [comment]
Yes version 4.4.3 is compatible with Big Sur.

You can get it on the [website](https://www.macenhance.com/cdock) or in the releases tab here.

**Comment by theobrinkman** [comment]
Hi

I bought the latest version. (4)
In version 3 I had theme brushed metal in 3 D .
[cid:image001.png@01D6BE7E.AC2215C0]
For that I had to put sliders like shown below.
[cid:image002.png@01D6BE7E.AC2215C0]
Now in the new version, I don’t get the 3D version.
What can I do?

Met vriendelijke groet,
Theo Brinkman

Van: Wolfgang Baird <notifications@github.com>
Beantwoorden - Aan: w0lfschild/cDock-Issue-Tracker <reply@reply.github.com>
Datum: dinsdag 17 november 2020 om 19:10
Aan: w0lfschild/cDock-Issue-Tracker <cDock-Issue-Tracker@noreply.github.com>
CC: Theo Brinkman <theobrinkman@outlook.com>, Author <author@noreply.github.com>
Onderwerp: Re: [w0lfschild/cDock-Issue-Tracker] Big Sur compatiblity (#296)


Yes version 4.4.3 is compatible with Big Sur.

You can get it on the website<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.macenhance.com%2Fcdock&data=04%7C01%7C%7Cc4aaad118dd143fdc86c08d88b24050d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637412334099843621%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sHcJwUmYheaZpMR36te%2BQ%2BtlfYVRxhQkLzG95lFMRn0%3D&reserved=0> or in the releases tab here.
